# Generated by Django 5.2.7 on 2025-11-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='line',
            field=models.CharField(choices=[('L1', 'Кировско-Выборгская'), ('L2', 'Московско-Петроградская'), ('L3', 'Невско-Василеостровская'), ('L4', 'Лахтинско-Правобережная'), ('L5', 'Фрунзенско-Приморская'), ('L6', 'Красносельско-Калининская'), ('L7', 'Кольцевая'), ('L8', 'Адмиралтейско-Охтинская')], default='L1', max_length=2, verbose_name='Линия метро'),
        ),
    ]
