# Generated by Django 5.2.7 on 2025-10-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together={('name', 'restaurant')},
        ),
        migrations.AddField(
            model_name='dish',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес или объём'),
        ),
        migrations.AddField(
            model_name='dish',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('г', 'г'), ('кг', 'кг'), ('мл', 'мл'), ('л', 'л')], default='г', max_length=2, null=True, verbose_name='Единица измерения веса или объёма'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu_update_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата обновления меню'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество в штуках'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время обновления'),
        ),
        migrations.RemoveField(
            model_name='dish',
            name='weight_grams',
        ),
    ]
