# Generated by Django 5.2.7 on 2025-10-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_dish_unique_together_dish_weight_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together={('name', 'restaurant', 'weight')},
        ),
    ]
