# Generated by Django 5.2.7 on 2025-10-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_dish_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu_url',
            field=models.URLField(blank=True, default=None, help_text='URL Яндекса', null=True, unique=True, verbose_name='Сайт меню'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_url',
            field=models.URLField(blank=True, help_text='URL стороннего сайта', null=True, verbose_name='Сайт ресторана'),
        ),
    ]
