# Generated by Django 5.2.7 on 2025-11-02 11:57

from django.db import migrations, models


def migrate_city_to_geodata(apps, schema_editor):
    RestaurantCity = apps.get_model('restaurant', 'City')
    GeodataCity = apps.get_model('geodata', 'City')

    GeodataCity.objects.bulk_create([
        GeodataCity(pk=rc.pk, name=rc.name)
        for rc in RestaurantCity.objects.order_by('pk')
    ])


def reverse_migrate_city_to_geodata(apps, schema_editor):
    RestaurantCity = apps.get_model('restaurant', 'City')
    GeodataCity = apps.get_model('geodata', 'City')

    RestaurantCity.objects.bulk_create([
        GeodataCity(pk=gc.pk, name=gc.name)
        for gc in GeodataCity.objects.order_by('pk')
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
        ('restaurant', '0005_alter_dish_restaurant_alter_restaurant_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='num_of_reviews',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество оценок'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='stations',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='geodata.station', verbose_name='Станции метро'),
        ),
        migrations.RunPython(migrate_city_to_geodata, reverse_migrate_city_to_geodata),
    ]
