# Generated by Django 5.2.7 on 2025-11-02 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
        ('restaurant', '0006_restaurant_latitude_restaurant_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='geodata.city', verbose_name='Город'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
