# Generated by Django 5.2.7 on 2025-11-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_restaurant_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
    ]
