# Generated by Django 5.2.7 on 2025-11-06 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_restaurant_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='stations',
        ),
    ]
