# Generated by Django 5.2.7 on 2025-11-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_remove_restaurant_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Ресторан считается действующим при рабочем URL', verbose_name='Действующий ресторан'),
        ),
    ]
