# Generated by Django 5.2.7 on 2025-11-14 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0002_alter_station_line'),
        ('restaurant', '0011_restaurant_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(default=0.0, verbose_name='Расстояние в км')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant', verbose_name='Ресторан')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodata.station', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Ближайшие станции ресторана',
                'verbose_name_plural': 'Ближайшие станции ресторанов',
                'unique_together': {('restaurant', 'station')},
            },
        ),
    ]
