# Generated by Django 5.2.7 on 2025-11-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_restaurantstation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
