name: CI

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      APP_NAME: sampo
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@v4

      - name: Create .env
        run:  |
          cp env/.env.local.example env/.env.local
          cp env/.env.test.example env/.env.test

      - name: Install make
        run: |
          sudo apt-get update
          sudo apt-get -y install make

      - name: Run containers
        run: make build

      - name: Run linter
        run: make linter

      # --- Separate step for mypy ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --only main,dev --no-root

      - name: Run mypy
        run: make mypyapp-ci APP=restaurant

      - name: Run tests
        run: make testall
